### ISSUE TITLE
error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by dong-lufei** [wildfirechat/vue-chat#61]
```
# 13697 @ donglufei in E:\test\wFVue-chat on git:master x [16:54:39]
$ npm run serve

> wf-web-chat@0.1.0 serve
> vue-cli-service serve --skip-plugins @vue/cli-plugin-eslint

 INFO  Starting development server...
10% building 2/2 modules 0 active(node:17268) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
10% building 2/4 modules 2 active ...\webpack-dev-server\client\index.js?http://192.168.31.120:8013&sockPath=/sockjs-nodeError: error:0308010C:digital envelope routines::unsupported    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)    at module.exports (E:\test\wFVue-chat\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (E:\test\wFVue-chat\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (E:\test\wFVue-chat\node_modules\webpack\lib\NormalModule.js:471:10)
    at E:\test\wFVue-chat\node_modules\webpack\lib\NormalModule.js:503:5
    at E:\test\wFVue-chat\node_modules\webpack\lib\NormalModule.js:358:12
    at E:\test\wFVue-chat\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (E:\test\wFVue-chat\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (E:\test\wFVue-chat\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at E:\test\wFVue-chat\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at runSyncOrAsync (E:\test\wFVue-chat\node_modules\loader-runner\lib\LoaderRunner.js:130:11)
    at iterateNormalLoaders (E:\test\wFVue-chat\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
    at Array.<anonymous> (E:\test\wFVue-chat\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (E:\test\wFVue-chat\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at E:\test\wFVue-chat\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:910% building 2/5 modules 3 active ...est\wFVue-chat\node_modules\babel-loader\lib\index.js!E:\test\wFVue-chat\src\main.jsnode:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (E:\test\wFVue-chat\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (E:\test\wFVue-chat\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (E:\test\wFVue-chat\node_modules\webpack\lib\NormalModule.js:471:10)
    at E:\test\wFVue-chat\node_modules\webpack\lib\NormalModule.js:503:5
    at E:\test\wFVue-chat\node_modules\webpack\lib\NormalModule.js:358:12
    at E:\test\wFVue-chat\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (E:\test\wFVue-chat\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (E:\test\wFVue-chat\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (E:\test\wFVue-chat\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at E:\test\wFVue-chat\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
    at E:\test\wFVue-chat\node_modules\graceful-fs\graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.15.0
```

**Comment by imndx** [comment]
执行`npm install`了吗？

**Comment by dong-lufei** [comment]
> 执行`npm install`了吗？

运行前，依赖肯定安装了呀。
最后找到原因了 是环境问题，比如nodejs版本过高，网上说大于等于17版本就有可能，网上还说react-scripts版本要大于5，等等
